events {}

http {
  upstream capacity_app {
    zone capacity_app 64k;
    server app-a:4000 max_fails=1 fail_timeout=2s;
    server app-b:4000 max_fails=1 fail_timeout=2s;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://capacity_app;
      proxy_connect_timeout 500ms;
      proxy_read_timeout 3s;
      proxy_next_upstream error timeout http_502 http_503 http_504;
      proxy_next_upstream_tries 2;

      add_header X-Load-Balancer capacity-lab always;
    }
  }
}
